### ISSUE TITLE
Broken with nodejs 18.6

### ISSUE THREAD

**Issue by Yaya48** [MenuDocs/erela.js#180]
Hello, since nodejs 18.6 it does not work anymore

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (C:\Users\yaya\Desktop\testode_modules\petitio\dist\index.js:30:574)
    at ke.json (C:\Users\yaya\Desktop\test\node_modules\petitio\dist\index.js:30:2499)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by FabrizioCoder** [comment]
I have the same problem

**Comment by saboooor** [comment]
Use this fork of erela.js
https://www.npmjs.com/package/@phamleduy04/erela.js
