### ISSUE TITLE
updateVoiceState on the client issue

### ISSUE THREAD

**Issue by Nolife159159** [MenuDocs/erela.js#181]
When im trying to update Voice State for my client im getting 
`
RangeError: No available nodes.
    at new Player (/root/DiscordBot/node_modules/erela.js/dist/structures/Player.js:82:19)
    at Player.create (/root/DiscordBot/node_modules/erela.js/dist/structures/Manager.js:205:16)
    at module.exports.run (/root/DiscordBot/src/commands/music/play.js:37:31)
    at runCommand (/root/DiscordBot/src/events/interaction/applicationCommand.js:10:23)
    at module.exports (/root/DiscordBot/src/events/interaction/applicationCommand.js:4:56)
    at botukas.emit (node:events:527:28)
    at interactionEvents.handleSlashCommands (/root/DiscordBot/src/utils/managers/interactionManager.js:30:21)
    at interactionEvents.handleInteractionTypes (/root/DiscordBot/src/utils/managers/interactionManager.js:16:22)
    at botukas.<anonymous> (/root/DiscordBot/src/utils/managers/interactionManager.js:7:67)
    at botukas.emit (node:events:539:35)
    at InteractionCreateAction.handle (/root/DiscordBot/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12)
    at Object.module.exports [as INTERACTION_CREATE] (/root/DiscordBot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/root/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/root/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/root/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/root/DiscordBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)`
   
    
    im using like this 
    `  client.on('raw', async(data) => {
    client.player.updateVoiceState(data)
  }) 
  `
  
  also on ready event i have this
  
  `const player = new Player(client)
    client.player = player
    player.init(client.user.id)`

**Comment by saboooor** [comment]
read the error, you have no nodes connected/configured

**Comment by Nolife159159** [comment]
well already fixed su we can close this PR
