### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by XeonE52680v3** [MenuDocs/erela.js#183]
I have a problem that makes it impossible for me to test. How to solve it now? Here is the log:
```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (D:\dreamvast\Dreamvast-slash\node_modules\petitio\dist\index.js:30:574)
    at ke.json (D:\dreamvast\Dreamvast-slash\node_modules\petitio\dist\index.js:30:2499)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

And this is my play audio code:
```
...
        if (interaction.options.getSubcommand() === "play") {
            const value = interaction.options.get("input").value;
            const msg = await interaction.editReply(`${client.i18n.get(language, "music", "play_loading")}`);
            
            const { channel } = interaction.member.voice;
            if (!channel) return msg.edit(`${client.i18n.get(language, "music", "play_invoice")}`);
            if (!interaction.guild.members.cache.get(client.user.id).permissions.has(PermissionsBitField.Flags.Connect)) return msg.edit(`${client.i18n.get(language, "music", "play_join")}`);
            if (!interaction.guild.members.cache.get(client.user.id).permissions.has(PermissionsBitField.Flags.Speak)) return msg.edit(`${client.i18n.get(language, "music", "play_speak")}`);
    
            const player = await client.manager.create({
                guild: interaction.guild.id,
                voiceChannel: interaction.member.voice.channel.id,
                textChannel: interaction.channel.id,
                selfDeafen: true,
            });
            
            const state = player.state;
            if (state != "CONNECTED") await player.connect();
            const res = await client.manager.search(value, interaction.user);
            if(res.loadType != "NO_MATCHES") {
                if(res.loadType == "TRACK_LOADED") {
                    player.queue.add(res.tracks[0]);
                    const embed = new EmbedBuilder()
                        .setDescription(`${client.i18n.get(language, "music", "play_track", {
                            title: res.tracks[0].title,
                            url: res.tracks[0].uri,
                            duration: convertTime(res.tracks[0].duration, true),
                            request: res.tracks[0].requester
                        })}`)
                        .setColor(client.color)
                    msg.edit({ content: " ", embeds: [embed] });
                    if(!player.playing) player.play();
                }
                else if(res.loadType == "PLAYLIST_LOADED") {
                    player.queue.add(res.tracks)
                    const embed = new EmbedBuilder()
                        .setDescription(`${client.i18n.get(language, "music", "play_playlist", {
                            title: res.playlist.name,
                            url: value,
                            duration: convertTime(res.playlist.duration),
                            songs: res.tracks.length,
                            request: res.tracks[0].requester
                        })}`)
                        .setColor(client.color)
                    msg.edit({ content: " ", embeds: [embed] });
                    if(!player.playing) player.play();
                }
                else if(res.loadType == "SEARCH_RESULT") {
                    player.queue.add(res.tracks[0]);
                    const embed = new EmbedBuilder()
                        .setDescription(`${client.i18n.get(language, "music", "play_result", {
                            title: res.tracks[0].title,
                            url: res.tracks[0].uri,
                            duration: convertTime(res.tracks[0].duration, true),
                            request: res.tracks[0].requester
                        })}`)
                        .setColor(client.color)
                    msg.edit({ content: " ", embeds: [embed] });
                    if(!player.playing) player.play();
                }
                else if(res.loadType == "LOAD_FAILED") {
                    msg.edit(`${client.i18n.get(language, "music", "play_fail")}`); 
                    player.destroy();
                }
            }
            else {
                msg.edit(`${client.i18n.get(language, "music", "play_match")}`); 
                player.destroy();
            }
        }
...
```

**Comment by CustomTag** [comment]
There is a new update in erela.js that should fix that problem with node.js v18.6.0 and higher!

Just run, npm i erela.js or yarn add erela.js
Then restart your bot and it should be fixed!

**Comment by XeonE52680v3** [comment]
Thanks, its fixed
