### ISSUE TITLE
Cannot read properties of undefined (reading 'map') : Manager.js:155:36

### ISSUE THREAD

**Issue by realpukhraj** [MenuDocs/erela.js#186]
TypeError: Cannot read properties of undefined (reading 'map')
    at Manager.<anonymous> (D:\Real\node_modules\erela.js\dist\structures\Manager.js:155:36)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Real\node_modules\erela.js\dist\structures\Manager.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by realpukhraj** [comment]
Solved
