### ISSUE TITLE
Petitio is showing error do something instantly 

### ISSUE THREAD

**Issue by realpukhraj** [MenuDocs/erela.js#190]
```js
0|main     | SyntaxError: Unexpected token  in JSON at position 0
0|main     |     at JSON.parse (<anonymous>)
0|main     |     at Y.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:574)
0|main     |     at ke.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:2499)
0|main     |     at runMicrotasks (<anonymous>)
0|main     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by Abadima** [comment]
Same issue over here

**Comment by Alfr3XD** [comment]
I also have the same error

**Comment by melike2d** [comment]
Build branch no longer uses petitio:

`npm install menudocs/erela.js#build`
or
`yarn add menudocs/erela.js#build`
