### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0 on Linux.

### ISSUE THREAD

**Issue by rem-9999** [MenuDocs/erela.js#195]
A file that actually worked on Windows doesn't work on Linux.

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (/home/remuring/Desktop/remuring/Music/node_modules/petitio/dist/index.js:30:574)
    at ke.json (/home/remuring/Desktop/remuring/Music/node_modules/petitio/dist/index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Node.makeRequest (/home/remuring/Desktop/remuring/Music/src/Extenders/Node.js:39:12)
    at async /home/remuring/Desktop/remuring/Music/node_modules/erela.js/dist/structures/Manager.js:152:25

When using player.serach() in Linux, the above error is returned
I am using the Build version of erela.js
Is this a problem with my OS? Has anyone got the same error as me on Linux?

OS : Ubuntu 20.04.5 LTS
NodeJS : 16.17.1

**Comment by Anish-Shobith** [comment]
its using petitio, the library was removed and replaced with unidici, you have to install erela.js via github
