### ISSUE TITLE
Some plugins does not work after latest update

### ISSUE THREAD

**Issue by emirkabal** [MenuDocs/erela.js#197]
I'm using erela.js-deezer and erela.js-filters and does not work after latest update. 

```bash
C:\Users\emirk\Projects\kabalsbot\bot\node_modules\erela.js\dist\structures\Manager.js:102
                    throw new RangeError(`Plugin at index ${index} does not extend Plugin.`);
                          ^
RangeError: Plugin at index 2 does not extend Plugin.
    at new Manager (C:\Users\emirk\Projects\kabalsbot\bot\node_modules\erela.js\dist\structures\Manager.js:102:27)
    at exports.default (C:\Users\emirk\Projects\kabalsbot\bot\src\utils\MusicOptions.ts:12:19)
    at new CustomClient (C:\Users\emirk\Projects\kabalsbot\bot\src\modules\CustomClient.ts:60:30)
    at Object.<anonymous> (C:\Users\emirk\Projects\kabalsbot\bot\src\bot.ts:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (C:\Users\emirk\Projects\kabalsbot\bot\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\emirk\Projects\kabalsbot\bot\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
```

Solution for now:
I fixed this problem with downgrading erela.js [#2e2e65cd9a](https://github.com/MenuDocs/erela.js/tree/2e2e65cd9a3bb3bffdc9ef4f4b9953f386096f28)
`yarn add MenuDocs/erela.js#2e2e65cd9a` or `npm install MenuDocs/erela.js#2e2e65cd9a`

**Comment by SerenModz21** [comment]
i do not use erela but this issue is not an erela issue. the problem is that `erela.js-deezer` and `erela.js-filters` haven't been updated in months and therefore uses outdated versions of erela

**Comment by emirkabal** [comment]
> i do not use erela but this issue is not an erela issue. the problem is that `erela.js-deezer` and `erela.js-filters` haven't been updated in months and therefore uses outdated versions of erela. whether my statement is true or not, i personally recommend u ask the plugin authors to update their packages.

Thank you for your response
